config/routes.rb
Getfitgo::Application.routes.draw do
  match 'auth/fitbit/callback', to: 'omniauth_callbacks#fitbit', via: [:get, :post]
  match 'auth/moves/callback', to: 'omniauth_callbacks#moves', via: [:get, :post]
  match 'auth/facebook/callback', to: 'omniauth_callbacks#facebook', via: [:get, :post]
  match 'auth/google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  get "/policy" => "static_pages#policy"
  get "/terms_and_conditions" => "static_pages#tnc"
  namespace :questionnaires do
    resources :surveys
    resources :attempts, :only => [:new, :create,:update,:edit]
  end

  root to: 'homes#index'
  resource :dashboard, only: [:show]
  devise_for :users, path_names: {sign_in: 'login', signout: 'logout'}, controllers: {:invitations => 'invitations', :registrations => 'registrations', confirmations: 'confirmations'}

  match '/signup/:invitation_token', :controller => 'users', :action => 'new', via: :get, as: :signup

  resources :users, only: [:show] do
    resources :teams, except: [:edit, :update, :destroy]
    resource :reports, only: [:show]

  end
  resources :teams, only: [:new, :index, :show, :create] do
    post 'join' => 'memberships#create'
    resources :challenges, only: [:create, :show, :index] do
      post 'join' => 'user_activities#create'
      post 'choose' => 'team_activities#create'
    end
  end
  resources :users, only: [:show] do
    resource :report, only: :show
  end
  resources :monthly_challenges, controller: :challenges
  resources :challenges, only: [:create, :show] do
    post 'join' => 'user_activities#create'
    resources :teams, only: [:new, :create, :show] do
      post 'join' => 'memberships#create'
    end
  end
  get '/contacts/:importer/callback' => 'contacts#contacts_callback'
  get '/contacts/contacts_callback'
  resources :user_invitation_team, only: [:new]
  devise_scope :user do
    match '/team/:id/invite' => 'invitations#team', via: [:get, :post]
    post 'batch_invite' => 'invitations#batch_invite'
    get '/registrations/resend' => 'registrations#resend'
    get '/registrations/welcome_page' => 'registrations#welcome_page'
    get '/introduction' => 'registrations#introduction'
    get '/update_profile' => 'registrations#update_profile'
  end
  get '/oauth2callback' => 'contacts#contacts_callback'
  resources :daily_activities, only: [:create, :update]
  resources :team_activities, only: :update
  resources :user_activities, only: :update
  post 'sync' => 'user_activities#sync'

  resources :identities, :only => :destroy
  get 'post_registrations' => 'social_sharing#post_registrations', as: :post_registrations
  post 'post_badge_won' => 'social_sharing#post_badge_won', as: :post_badge_won
  get 'post_challenge_join/:id' => 'social_sharing#post_challenge_join', as: :post_challenge_join
  get 'post_challenge_completion/:id' => 'social_sharing#post_challenge_completion', as: :post_challenge_completion

  resources :friendships, only: [:create, :edit, :destroy]

  resources :activity, only: [] do
    post 'wow' => 'activities#wow'
    delete 'unwow' => 'activities#unwow'
  end
  resources :action_messages, only: [:new] do
    collection { post :import }
  end
  resources :posts, only: [:create, :destroy]

  resources :comments, only: [:create, :destroy, :update] do
  end

  post '/request_invite' => 'users#request_invite', as: :request_invite
  get '/activities/view_more' => 'activities#view_more'

  get '/notifications/unread' => 'notifications#unread'
  put '/notifications/mark_as_read' => 'notifications#mark_as_read'
  get '/notifications/refresh' => 'notifications#refresh'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_comment.html.erb
<div class="CL"></div>
<% if (!(current_user.eql?(user)) && current_user.mutual_friends.include?(user)) || current_user.eql?(user) %>
  <div class="postBx comment" style="margin-top: 0px; background: #cacaca">
    <%= form_tag(comments_path, remote: true) do %>
      <div class="field">
        <%= text_area_tag 'body', nil, placeholder: "Write a comment...", class: "form-control", style: 'width: 100%;'  %>
        <!-- <label class="camIcon" > -->
         <%#= f.file_field :image,style:"display:none;" %>
        <!-- </label> -->
        <%= hidden_field_tag 'commentable_id', commentable.id %>
        <%= hidden_field_tag 'commentable_type', commentable.class.to_s %>
        <%= hidden_field_tag 'parent_id', parent_id %>
        <%= hidden_field_tag 'user_id', current_user.id  %>
        <%= hidden_field_tag 'activity_feed_user_id', @user.id %>
      </div>
      <p align="right">
        <!-- <img src="/wh-smiley.png" width="16" height="16" alt="" class="vm-mr-5"> -->
        <input id="post-comment-button" class="btn-branding btn" name="commit" type="submit" value="Comment" data-disable-with="Please wait ...">
      </p>
    <% end %>
  </div>
 <% end %>

app/views/shared/_post_form.html.erb
<div class="postBx">
  <%= form_for(Post.new,remote: true) do |f| %>
    <div class="field">
      <%= f.text_area :name, placeholder: "Share something interesting...",class: "form-control"  %>
      <%= hidden_field_tag 'user_id', @user.id  %>
    </div>
    <p align="right">
      <label>
        <i class="camIcon"></i>
        <%= f.file_field :image,style:"display:none;" %>
      </label>
      <span id="post_spinner" style="display:none;position:relative;float:left;margin-left:15%;margin-top:15%;"><img class="loader" src='/ajax-loader.gif'/></span>
      <%= f.submit "Post", class: "btn-branding btn", id: "post_button", onclick: "$('#post_spinner').show();", 'data-disable-with'.to_sym => "Please wait ..." %>
    </p>
  <% end %>
</div>

app/views/shared/_show_comment.html.erb
<% comment.each { |current_comment, child_comments| %>
  <div>
  	<div class="row">
      <div class="col-md-12" style="margin-top: 10px;">
        <div class="col-md-2">
          <%= image_tag current_comment.user.photo.url(:thumb), size: '40x40' %>
        </div>
        <div class="col-md-10">
          <p>
            <strong><%= link_to current_comment.user.user_name, user_path(current_comment.user.id), class: "colored-link show-comments" %></strong>
            <div style="text-align: justify">
              <% if current_comment.body.length > 200 %>
                <%= truncate(current_comment.body, length: 200) %>
                  <%= link_to_function 'Read more', "$(this).parent().html('#{escape_javascript current_comment.body}')", class: 'colored-link' %>
                <% else %>
                  <%= current_comment.body %>
                <% end %>
            </div>
          </p>
          <p>
            <span id="comment_<%= current_comment.id %>_comment_count"><%= render 'activities/comment_count', comment: current_comment %></span> <%= link_to "javascript:void(0);" do %>
              <i class="msgIcon" onclick="showComments('<%= current_comment.class.to_s %>','<%= current_comment.id %>')"></i>
            <% end %> <span style="float:right;"><%= local_time_ago(current_comment.created_at) %></span>
          </p>
        </div>
      </div>
    </div>
  </div><hr style="style-six"/>

  <div class="nest" id="<%= current_comment.class.to_s %>-<%= current_comment.id %>",  style="display: none">
    <div id="comments-<%= current_comment.id %>-<%= current_comment.class.to_s %>">
      <% child_comments.each { |parent_comment| %>
        <%= render 'shared/show_comment', comment: parent_comment, commentable: current_comment.commentable, user: user %>
      <% } if child_comments.present? %>
    </div>
    <div id="comment-<%= current_comment.id %>-<%= current_comment.class %>" style=" margin-top: 10px;"><%= render 'shared/post_comment', parent_id: current_comment.id, commentable: current_comment.commentable, user: user %></div>
  </div>
<% }  %>

<script type="text/javascript">
	$(".colored-link.show-comments").on('click', function() {
    var comment = document.getElementByClassName(".postBx").find(".nest");
    comment.style.display = ((comment.style.display != 'block') ? 'block' : 'none');
});
</script>

app/views/shared/_show_comments.html.erb
<!-- <%#= link_to_function pluralize(Comment.where(commentable: commentable).pluck(:user_id).uniq.count, 'person'), "$('#commentorsModal').modal('show');", class: 'colored-link' %> commented on this -->
<div id="comments-<%= commentable.id %>-<%= commentable.class.to_s %>">
  <% display_threaded_comments(commentable).each { |parent_comment| %>
    <%= render 'shared/show_comment', comment: parent_comment, user: user %>
  <% } %>
</div>
<div id="comment-<%= commentable.id %>-<%= commentable.class %>"><%= render 'shared/post_comment', commentable: commentable, parent_id: nil, user: user %></div>

<div class="modal fade" id="commentorsModal" tabindex="-1" role="dialog" aria-labelledby="commentorsLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content panel panel-info">
      <div class="modal-body postBx defaultColor">
      <ul>
        <% commentors = User.find(Comment.where(commentable: commentable).pluck(:user_id).uniq).each { |user| %>
          <li>
            <%= link_to user.user_name, user_path(user.id) %>
          </li>
        <% } %>
      </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sign_in_error.html.erb
<div class="row">
  <div class="col-md-8">
	<img src="">
	<H3>Hey,</H3>
	<h5>Thanks for your interest in getfitgo. We are currently a beta site,testing out key flows and are open by invitation only.</h5>

  <h5>We are glad to have users like you interested in checking out and using our platform. Please share your email ID below and we’ll send you an invitation as soon as we are ready.</h5>
  <input></input>
</div>
  <div class="col-md-4">
  <span>
  	<img src="placeholder.jpg">
  </span>
	
  </div>
</div>