config/routes.rb
Getfitgo::Application.routes.draw do
  match 'auth/fitbit/callback', to: 'omniauth_callbacks#fitbit', via: [:get, :post]
  match 'auth/moves/callback', to: 'omniauth_callbacks#moves', via: [:get, :post]
  match 'auth/facebook/callback', to: 'omniauth_callbacks#facebook', via: [:get, :post]
  match 'auth/google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  get "/policy" => "static_pages#policy"
  get "/terms_and_conditions" => "static_pages#tnc"
  namespace :questionnaires do
    resources :surveys
    resources :attempts, :only => [:new, :create,:update,:edit]
  end

  root to: 'homes#index'
  resource :dashboard, only: [:show]
  devise_for :users, path_names: {sign_in: 'login', signout: 'logout'}, controllers: {:invitations => 'invitations', :registrations => 'registrations', confirmations: 'confirmations'}

  match '/signup/:invitation_token', :controller => 'users', :action => 'new', via: :get, as: :signup

  resources :users, only: [:show] do
    resources :teams, except: [:edit, :update, :destroy]
    resource :reports, only: [:show]

  end
  resources :teams, only: [:new, :index, :show, :create] do
    post 'join' => 'memberships#create'
    resources :challenges, only: [:create, :show, :index] do
      post 'join' => 'user_activities#create'
      post 'choose' => 'team_activities#create'
    end
  end
  resources :users, only: [:show] do
    resource :report, only: :show
  end
  resources :monthly_challenges, controller: :challenges
  resources :challenges, only: [:create, :show] do
    post 'join' => 'user_activities#create'
    resources :teams, only: [:new, :create, :show] do
      post 'join' => 'memberships#create'
    end
  end
  get '/contacts/:importer/callback' => 'contacts#contacts_callback'
  get '/contacts/contacts_callback'
  resources :user_invitation_team, only: [:new]
  devise_scope :user do
    match '/team/:id/invite' => 'invitations#team', via: [:get, :post]
    post 'batch_invite' => 'invitations#batch_invite'
    get '/registrations/resend' => 'registrations#resend'
    get '/registrations/welcome_page' => 'registrations#welcome_page'
    get '/introduction' => 'registrations#introduction'
    get '/update_profile' => 'registrations#update_profile'
  end
  get '/oauth2callback' => 'contacts#contacts_callback'
  resources :daily_activities, only: [:create, :update]
  resources :team_activities, only: :update
  resources :user_activities, only: :update
  post 'sync' => 'user_activities#sync'

  resources :identities, :only => :destroy
  get 'post_registrations' => 'social_sharing#post_registrations', as: :post_registrations
  post 'post_badge_won' => 'social_sharing#post_badge_won', as: :post_badge_won
  get 'post_challenge_join/:id' => 'social_sharing#post_challenge_join', as: :post_challenge_join
  get 'post_challenge_completion/:id' => 'social_sharing#post_challenge_completion', as: :post_challenge_completion

  resources :friendships, only: [:create, :edit, :destroy]

  resources :activity, only: [] do
    post 'wow' => 'activities#wow'
    delete 'unwow' => 'activities#unwow'
  end
  resources :action_messages, only: [:new] do
    collection { post :import }
  end
  resources :posts, only: [:create, :destroy]

  resources :comments, only: [:create, :destroy, :update] do
  end

  post '/request_invite' => 'users#request_invite', as: :request_invite
  get '/activities/view_more' => 'activities#view_more'

  get '/notifications/unread' => 'notifications#unread'
  put '/notifications/mark_as_read' => 'notifications#mark_as_read'
  get '/notifications/refresh' => 'notifications#refresh'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  helper 'questionnaires/surveys'
  include ChallengesHelper
  include Questionnaires::SurveysHelper
  before_filter :authenticate_user!, only: [:show]

  def show
    @dashboard = UserDashboard.new(current_user)
    if current_user.mutual_friends.count > 0
      @posts = Post.from_friends_of(current_user)
      user_ids = ([current_user.id] + current_user.friend_ids + current_user.inverse_friend_ids).join(',')
      @posts = @posts.where("creator_id IN (#{user_ids})").where("user_id IN (#{user_ids})")
    else
      @posts = current_user.posts
    end
    @user = current_user
    @survey =  Survey::Survey.active.first
    @participant = current_user
    @attempt = Survey::Attempt.all.find_by_participant_id(current_user.id)
    if @attempt
      @unanswered_questions = attempt_unanswered_questions
    else
      @attempt = @survey.attempts.new
      @attempt.participant = current_user
      @attempt.save
      @unanswered_questions = @survey.questions
    end
    @unanswered_questions = [@unanswered_questions.first]
    unless @survey.nil?
      @attempt = @survey.attempts.new
      @attempt.answers.build
    end
    gon.count = current_user.identities.where("provider=? or provider=?","fitbit","moves").count
    @count = gon.count
    # if @attempt.nil?
    #   @attempt = @survey.attempts.new
    #   @attempt.answers.build
    #   @unanswered_questions = @survey.questions
    #   @unanswered_questions = [@unanswered_questions.first]
    # end
    # @attempt = Survey::Attempt.all.find_by_participant_id(current_user.id)
    # @unanswered_questions =  attempt_unanswered_questions
    # @unanswered_questions = [@unanswered_questions.first]
      # @participant = current_user # you have to decide what to do here
      # @survey =  Survey::Survey.active.first
      # @attempt = Survey::Attempt.all.find_by_participant_id(current_user.id)
      # if @attempt
      #   @unanswered_questions = attempt_unanswered_questions
      # else
      #   @unanswered_questions = @survey.questions
      # end
      # @unanswered_questions = [@unanswered_questions.first]
      # unless @survey.nil?
      #   @attempt = @survey.attempts.new
      #   @attempt.answers.build
      # end
  end

  def attempt_unanswered_questions
    Survey::Question.all.find(unanswered_questions_ids)
  end

  def unanswered_questions_ids
    all_questions.pluck(:id) - question_answered.pluck(:question_id)
  end

  def question_answered
    Survey::Attempt.all.find_by_participant_id(current_user.id).answers
  end

  def all_questions
    Survey::Attempt.all.find_by_participant_id(current_user.id).survey.questions
  end

  def link_to_remove_field(name, f)
    f.hidden_field(:_destroy) +
    link_to_function(raw(name), "removeField(this)", :id =>"remove-attach")
  end

  def new_survey
    new_questionnaires_survey_path
  end

  def edit_survey(resource)
    edit_questionnaires_survey_path(resource)
  end

  def survey_scope(resource)
    if action_name =~ /new|create/
      questionnaires_surveys_path(resource)
    elsif action_name =~ /edit|update/
      questionnaires_survey_path(resource)
    end
  end

  def new_attempt
    new_questionnaires_attempt_path
  end

  def attempt_scope(resource)
    if action_name =~ /new|create/
     questionnaires_attempts_path(resource)
    elsif action_name =~ /edit|update/
      questionnaires_attempt_path(resource)
    end
  end

  def link_to_add_field(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object,:child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "addField(this, \"#{association}\", \"#{escape_javascript(fields)}\")",
    :id=>"add-attach",
    :class=>"btn btn-small btn-info")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper

  def challenge_title challenge, user
    if challenge.not_warm_up?
      if current_user.eql? user
        'My 4-Week Training Plan'
      else
        user.user_name.split(' ').first + "'s 4-Week Training Plan"
      end
    else
      'Warm up <span class="hidden-xs">to</span> <span class="hidden-xs" style="color:#00c8c8">get</span><span class="hidden-xs" style="color:#fa9600">fit</span><span class="hidden-xs" style="color:#00c8c8">go</span>'.html_safe

    end
  end

  def challenge_details challenge, view_challenge
    if challenge.not_warm_up?
      (link_to 'View challenge', challenge, :style => 'float: right') if view_challenge
    else
      (link_to 'View warm up', introduction_path, :style => 'float: right') if view_challenge
    end if challenge.participating_users.include? current_user
  end

  def steps_to_minutes steps
    minutes = steps/126.2
    minutes = (minutes/5.0).ceil * 5
  end
end

app/views/dashboards/_badges.html.erb
<div class="widgetTitle">
  <span>Achievements</span>
  <!--<a href="#." class="FR">View All CHALLENGES</a>-->
  <div class="CL"></div>
</div>
<div class="widgetCnt">
  <br/><%= render 'dashboards/badges_carousel', :user => user %>
            <% if current_user.identities.find_by(provider: "facebook") %>
              <% if (current_user.eql? user) && user.has_achievements? %>
                Share your <%= user.last_won_badge.name %>
                badge <%= link_to image_tag('/ufb.png',id:"fb"), post_badge_won_path(user.last_won_badge) %>
              <% end %>
            <% end %>
</div>

app/views/dashboards/_current_challenge_modal.html.erb
<% challenge_dates = current_user.current_challenge.dates %>

<div class="modal fade" id="currentChallengeModal" tabindex="-1" role="dialog" aria-labelledby="updateProfileModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content panel panel-default">
      <div class="modal-header panel-heading brand" style="background: #fff;">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h5 class="modal-title" id="welcomeModalLabel" style="color: #646464;">
          <div class="col-xs-12 " style="text-align: center; font-family: 'Flexo Demi';">
            <p>Congratulations! You've completed your 7-day warm up and earned <%= if current_user.badges.count > 0; pluralize(current_user.badges.count, 'badge') + " and "; end %> <%= current_user.score %> points.<br/>
              Now start an exciting 4-Week Training Plan - <span class="lBluTxt">Walk <%= current_user.current_challenge.challenge.number_of_steps %> Steps in 4 Weeks</p>
            </div>
          </h5>
          <div class="CL"></div>
        </div>
        <div class="modal-body col-md-12">
          <div class="col-md-12">
          <span class="head_modal">YOUR 4-WEEKS TRAINING PLAN</span>
            <span class="modal_link"><%= link_to 'VIEW CHALLENGE', challenge_path(current_user.current_challenge.challenge.id), style: "color: #faaf00;", target: '_blank' %></span>
          </div>
          <div class="col-md-6 hidden-xs leftcontainer">
            <div class="run col-md-2 hidden-xs hidden-sm"><img src="/walk_man_round.png"></div>
            <div class="col-md-10 hidden-xs"> <span class="greyTitle">Walk <%= current_user.current_challenge.challenge.number_of_steps %> in 4 Weeks</span>
              <p class="greyTxt" id="date_challenge"><%= challenge_dates.first.strftime('%d/%m/%Y') %> to <%= challenge_dates.last.strftime('%d/%m/%Y') %></p>
              <% if current_user.current_challenge.challenge.user_activities.count > 1 %>
                <p class="greyTxt" style="float: right;"><span class="blueTxt"><%= link_to "#{pluralize((current_user.current_challenge.challenge.user_activities.count - 1), 'member')}", current_user.current_challenge.challenge, class:"colored-link" %></span> participating.</p>
              <% end %>
              <div class="CL"></div>
              <div class="bigText hidden-sm"><%= current_user.current_challenge.challenge.number_of_minutes %></div>
              <span class="col-md-3"></span>
              <span class="centered col-md-6">minutes of focused walking each day.</span>

              <div class="CL"></div>
                <% if current_user.identities.find_by(provider: "facebook") %>
                  <%= link_to image_tag('/ufb.png',id:"fb"), post_challenge_join_path(current_user.current_challenge.challenge), class: "share col-md-4", style: 'margin-left: -6.5em; padding-top: 3.5em;' %>
                <% end %>
              <div class="CL"></div>
            </div>
          </div>
          <div class="col-md-6 col-xs-12 rightcontainer">
           <div class="col-md-12 first">
            <span class="col-md-2 col-xs-2"><img id="map_img" src="/map.png"></span>
            <span class="col-md-9 "><span class="blueTxt"><p>TRACK</p></span>
              <p>Carry your tracker with you & track your daily activity</p>
            </span>
          </div>
          <div class="col-md-12 second">
            <span class="col-md-2 col-xs-2"><img id="chart_img" src="/chart.png"></span>
            <span class="col-md-9"><span class="blueTxt"><p>UPDATE</p></span>
              <p>your daily activity on your getfitgo dashboard</p>
            </span>
          </div>
          <div class="col-md-12 third">
            <span class="col-md-2 col-xs-2"><img id="heart_img" src="/heart.png"></span>
            <span class="col-md-9"><span class="blueTxt"><p>#FEELGOODNOW</p></span>
              <p>Get expert feedback on fitness and diet. Earn Rewards</p>
            </span>
          </div>
          <div class="col-md-12">
            <div class="col-md-7"></div>
            <div class="col-md-4"><button type="button" class="btn btn-branding" data-dismiss="modal" aria-hidden="true">GET STARTED</button></div>
          </div>
        </div>

      </div>
      <!-- <div class="modal-footer panel-footer no-margin brand" style="text-align: center; background: #fff; padding-top: 0.5em; border-top: 1em solid #646464; font-family:'Flexo Demi';">
        <p style="padding-top: 1.3em;"></p>Your 4-Week Training Plan will start as you soon as you finish your warm up. Keep your profile and activity data updated for our experts to recommend your 4-Week Training Plan.
      </div> -->
    </div>
  </div>
</div>

app/views/dashboards/_daily_input_modal.html.erb
<div class="modal fade" id="dailyInputModal" tabindex="-1" role="dialog" aria-labelledby="dailyInputModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header widgetTitle">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <span class="modal-title" id="dailyInputModalLabel">Update Daily Activity</span>
        <div class="CL"></div>
      </div>
      <div class="modal-body postBx">
        <%= render 'dashboards/daily_input', daily_activity: daily_activity %>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_lifestyle_check_dob.html.erb
<div class="widgetTitle headLine1 widgetnew" >
  <span>YOUR DATE OF BIRTH</span>
  <div class="CL"></div>
</div>
<div class="widgetCnt" id="questions" class="lifestyle_check_dob" style="padding-bottom: 40px;">
  <div class="row">
  <span class="col-md-1"><img src="/Personal Information.png"></span>
    <p> Tell us about your lifestyle and get personalised tips and recommendations from our experts.</p>
    <p>Your date of birth</p>
  </div>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6" >
     <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:method => :put, :multipart => true}, :remote => true) do |f| %>
      <div class="input-group date" style="margin-top: 20px;">
          <div class="row" style="margin-bottom: 1em;">
            <div class="col-md-3" style="padding-top: 10px;">
              <%= f.label :birth_date %>
            </div>
            <div class="col-md-9">
              <div class="input-group date">
                <%= f.text_field :birth_date, placeholder: "DD/MM/YYYY", :autocomplete => "off",class: "form-control",'data-behaviour'.to_sym => 'datepicker','data-max'.to_sym => "01/01/#{18.years.ago.year}", :value => if resource.birth_date; resource.birth_date.strftime('%d/%m/%Y') end %><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
              </div>
            </div>
          </div>
        </div>
        <%= f.hidden_field :tab, :value => from %>
        <div class="row">
          <div class="col-md-12">
            <div class="col-md-5"></div>
            <div class="col-md-4">
             <%= f.submit 'Update', class:'btn-branding continue-bt btn' %>
             </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboards/_lifestyle_profile_widget.html.erb
 <% if !@unanswered_questions.first.nil? %>
    <%= render 'dashboards/lifestyle_check_question', attempt: @attempt %>
  <% elsif !user.bmi.is_a? Float %>
    <%= render 'dashboards/lifestyle_check_bmi' %>
  <% elsif !user.age %>
      <%= render 'dashboards/lifestyle_check_dob',resource: user, resource_name:"user", from:"DOB_dashboard" %>
  <% end %>

app/views/dashboards/_warm_up_started_content.html.erb
<div class="widgetBx">
  <p style="color: #006464; font-weight: bold">What's next ...</p>
  <div class="widgetCnt">
    <div class="col-xs-12">
      <div class="col-md-4">
        <div class="row">
          <div style="text-align: center"><%= image_tag '/track.png', size: '100x100' %></div>
        </div>
        <div style="text-align: center"><strong>TRACK</strong></div>
        <p style="line-height: 1"></p>
        <p style="text-align: center">Track your daily steps and calories burnt with your <span style="color:#00c8c8">get</span><span style="color:#fa9600">fit</span><span style="color:#00c8c8">go</span> device</p>
      </div>

      <div class="col-md-4">
        <div class="row">
          <div style="text-align: center"><%= image_tag '/Update.png', size: '100x100' %></div>
          <div style="text-align: center"><strong>UPDATE</strong></div>
          <p style="line-height: 1"></p>
          <p style="text-align: center">
            Update it on your <span style="color:#00c8c8">get</span><span style="color:#fa9600">fit</span><span style="color:#00c8c8">go</span> <%= link_to 'dashboard', dashboard_path %> & review your progress
          </p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="row">
          <div style="text-align: center"><%= image_tag '/Feedback.png', size: '100x100' %></div>
        </div>
        <div style="text-align: center"><strong>FEEDBACK</strong></div>
        <p style="line-height: 1"></p>
        <p style="text-align: center">Your <span style="color:#00c8c8">get</span><span style="color:#fa9600">fit</span><span style="color:#00c8c8">go</span> personal trainer tracks your progress, provides personal feedback and tips and plans what’s next and best for you</p>
      </div>
    </div>
    <div class="CL"></div>
    <div class="row">
      <p style="line-height: 1"></p>
      <ul class="" style="line-height: 2 !important;">
        <li>
          <i class=""></i> Your first 4-Week Training Plan starts immediately after the warm up stage (first week)
        </li>
        <li>
          <i class=""></i> Keep walking, running and being active like you have always been doing and see how you breeze through the challenge
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/dashboards/_weekly_update_modal.html.erb
<% week_number = ((Date.today - current_user.current_challenge.start_time.to_date).to_i + 1)/7 %>
<% week = (week_number.eql? 1) ? 'second' : (week_number.eql? 2) ? 'third' : 'fourth'  %>
<% applicable_daily_activities = current_user.current_challenge.daily_activities.where.not(steps_covered: nil).where(start_time: [(Date.today - 7.days)...Date.today]) %>
<% less_activity_data = applicable_daily_activities.count <= 3 %>
<% best_performance = applicable_daily_activities.order(steps_covered: :desc).first %>
<% worst_performance = applicable_daily_activities.order(steps_covered: :desc).last %>
<% weekly_average = (applicable_daily_activities.sum(:steps_covered)/applicable_daily_activities.count).round(0) rescue applicable_daily_activities.sum(:steps_covered) %>
<% applicable_achievements = Achievement.where(user_id: current_user.id).last(3) %>
<% leaders_ids = current_user.current_challenge.challenge.user_activities.where(status: 'Progress').select { |ua| ua.updated_daily_activities.count >= 5 }.map(&:user_id) %>
<% leader = User.find(leaders_ids).sort_by { |user| -user.current_challenge.average }.first %>
<% leader_name = if leader.eql? current_user; 'You'; else; leader.user_name.split(' ').first if leader; end; %>
<% applicable_points = Point.where(user_id: current_user.id, created_at: [(Date.today - 6.days)..Date.today]).sum(:score) %>
<% badges_to_be_won = Badge.where("badges.id NOT IN (?)", current_user.badges.pluck(:id)).to_a.sort_by{rand}.first(4) %>
<% achievements_to_be_unlocked = []; achievements_to_be_unlocked << badges_to_be_won; achievements_to_be_unlocked.flatten!  %>

<div class="modal fade" id="weeklyUpdateModal" tabindex="-1" role="dialog" aria-labelledby="weeklyUpdateModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content panel panel-default">
      <div class="modal-header panel-heading brand">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h5 class="modal-title" id="weeklyUpdateModalLabel" style="color: #646464;">
          <div class="col-xs-12" style="text-align: center; font-family: 'Flexo Demi';">
            <div class="run col-xs-offset-1 col-xs-1 hidden-xs hidden-sm">
              <img src="/walk_man_round.png">
            </div>
            <div class="col-xs-10" style="text-align: left; margin-top: 15px; font-size: 125%;">
              <strong>You’re into your <%= week %> week of the challenge. <% if less_activity_data %>We’ve been missing you.<% else %>How do you feel?<% end %></strong>
            </div>
          </div>
          </h5>
          <div class="CL"></div>
        </div>
        <div class="modal-body col-md-12" style="text-align: center;padding-bottom: 30px;">
          <div class="col-md-12" style="text-align: justify;">
          <span class="head_modal" style="color: #009696">YOUR 4-WEEK TRAINING PLAN</span>
            <span class="modal_link"><%= link_to 'VIEW CHALLENGE', challenge_path(current_user.current_challenge.challenge.id), style: "color: #faaf00;", target: '_blank' %></span>
          </div>
          <div class="col-md-6 leftcontainer">
            <div class="col-md-12">
              <strong style="color: #009696">
                  <% if less_activity_data %>We’ve been missing you.<% else %>Weekly digest<% end %>
              </strong><br/><br/>
              <p style="float: right;">
                <% if less_activity_data %>
                  We haven't heard much from you. Have you been tracking your daily activity? Update your steps and calories burned on <span style="color:#00c8c8">get</span><span style="color:#fa9600">fit</span><span style="color:#00c8c8">go</span> and get feedback from our Coaches. <%= link_to 'Update activity', "javascript:void(0);", class: 'colored-link', 'data-toggle'.to_sym => "modal", 'data-target'.to_sym => "#dailyInputModal", 'data-dismiss'.to_sym => "modal" %>
                <% else %>
                  <% if week_number.eql? 1 %>
                    Consistency is key in creating a new habit, so be sure that you get something in at least 5 days a week.
                  <% elsif week_number.eql? 2 %>
                    It's ok to take a day off once a week or choose a day to pursue any other fitness activity. Spice it up a bit!
                  <% else %>
                    Try cycling instead of walking for a few days and work your leg muscles.
                  <% end %>
                <% end %>
              </p>
              <div class="CL"></div>
              <div class="bigText"><%= current_user.steps_to_minutes({pure: true}) %></div>
              <span class="col-md-3"></span>
              <strong><span class="centered col-md-6" style="font-size: 110%">more minutes each day</span></strong>

              <div class="CL"></div>
            </div>
          </div>
          <div class="col-md-6 rightcontainer">
            <div class="col-xs-12 first">
              <% offset = (less_activity_data && leader.nil?) ? 'col-xs-offset-4' : (leader.nil? || less_activity_data) ? 'col-xs-offset-2' : '' %>
              <% if best_performance %>
                <div class="col-xs-4 <%= offset %>">
                  <p style="min-height: 25px;"><strong style="color: #009696;">Best Day</strong><p>
                  <p><%= best_performance.steps_covered %> steps</p>
                  <p><%= best_performance.start_time.strftime("#{best_performance.start_time.day.ordinalize} %B") %></p>
                </div>
              <% end %>
              <% unless less_activity_data %>
                <% offset = (best_performance.nil? && leader.nil?) ? 'col-xs-offset-4' : (leader.nil? || best_performance.nil?) ? 'col-xs-offset-2' : '' %>
                <div class="col-xs-4 <%= offset %>">
                    <p style="min-height: 25px;"><strong style="color: #009696;">Week's Average</strong></p>
                    <p><%= weekly_average %> steps</p>
                </div>
              <% end %>
              <% if leader %>
                <% offset = (best_performance.nil? && less_activity_data) ? 'col-xs-offset-4' : (less_activity_data || best_performance.nil?) ? 'col-xs-offset-2' : '' %>
                <div class="col-xs-4 <%= offset %>">
                  <p style="min-height: 25px;"><strong style="color: #009696;">Performer of the Week</strong></p>
                  <p><%= link_to leader_name, user_path(leader.id), method: :get, target: '_blank', class: 'btn btn-sm btn-branding', style: 'background-color: #009696;font-size: 10px !important;margin-top: 5px;' %></p>
                </div>
              <% end %>
              <div class="CL"></div>
              <p style="text-align: center;"><strong><%= link_to 'How have others been doing?', challenge_path(current_user.current_challenge.challenge.id) %></strong></p>
            </div>
            <div class="CL"></div>
            <div style="border: 1px solid #e1e1e1;">
              <p></p>
              <div class="col-md-12 second">
                <% unless less_activity_data %>
                  <p style="text-align: justify;"><strong style="color: #009696;">Achievements this week</strong></p>
                  <% unless applicable_achievements.empty? && (applicable_points.eql? 0) %>
                    <% unless applicable_achievements.empty? %>
                      <div class="col-md-8">
                        <div class="row">
                          <% applicable_achievements.each { |badge| %>
                            <div class="col-xs-4" style="text-align: center; width: 25%;<%= unless badge.is_a?(StreakBadge); 'margin-left: 10px; margin-right: 10px;'; end  %>">
                              <%= image_tag badge.badge.image, rel: 'tooltip', title: "#{badge.badge.name}", style: "#{unless badge.is_a?(StreakBadge); "margin-left: 10px; margin-right: 10px; #{if badge.is_a?(CummulativeBadge); 'margin-top: 5px;'; end }"; end }" %>
                            </div>
                          <% } %>
                        </div>
                      </div>
                    <% end %>
                    <div class="col-md-4" style="margin-top: 15px;white-space: nowrap">
                      <p><strong><%= applicable_points %> points</strong></p>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <div class="col-md-12 third">
                <p style="text-align: justify;"><strong style="color: #009696;">Achievements to be unlocked</strong></p>
                <div class="row">
                  <% achievements_to_be_unlocked.each { |badge| %>
                    <div class="col-xs-4" style="text-align: center; width: 25%;">
                      <%= image_tag badge.image, class: 'greyed-out', rel: 'tooltip', title: "#{badge.name}", style: "#{unless badge.is_a?(StreakBadge); "margin-left: 10px; margin-right: 10px; #{if badge.is_a?(CummulativeBadge); 'margin-top: 5px;'; end }"; end }" %>
                    </div>
                  <% } %>
                </div>
              </div>
              <div class="CL"></div>
            </div>
            <% if current_user.identities.find_by(provider: "facebook") %>
              <%#= link_to image_tag('/ufb.png',id:"fb"), post_challenge_join_path(current_user.current_challenge.challenge), class: "share FR col-md-4", style: "padding-top: 2em;" %>
            <% end %>
            <div class="CL"></div>
          </div>
        </div>
      <!-- <div class="modal-footer panel-footer no-margin brand" style="text-align: center; background: #fff; padding-top: 0.5em; border-top: 1em solid #646464; font-family:'Flexo Demi';">
        <p style="padding-top: 1.3em;"></p>Your 4-Week Training Plan will start as you soon as you finish your warm up. Keep your profile and activity data updated for our experts to recommend your 4-Week Training Plan.
      </div> -->
    </div>
  </div>
</div>