config/routes.rb
Getfitgo::Application.routes.draw do
  match 'auth/fitbit/callback', to: 'omniauth_callbacks#fitbit', via: [:get, :post]
  match 'auth/moves/callback', to: 'omniauth_callbacks#moves', via: [:get, :post]
  match 'auth/facebook/callback', to: 'omniauth_callbacks#facebook', via: [:get, :post]
  match 'auth/google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  get "/policy" => "static_pages#policy"
  get "/terms_and_conditions" => "static_pages#tnc"
  namespace :questionnaires do
    resources :surveys
    resources :attempts, :only => [:new, :create,:update,:edit]
  end

  root to: 'homes#index'
  resource :dashboard, only: [:show]
  devise_for :users, path_names: {sign_in: 'login', signout: 'logout'}, controllers: {:invitations => 'invitations', :registrations => 'registrations', confirmations: 'confirmations'}

  match '/signup/:invitation_token', :controller => 'users', :action => 'new', via: :get, as: :signup

  resources :users, only: [:show] do
    resources :teams, except: [:edit, :update, :destroy]
    resource :reports, only: [:show]

  end
  resources :teams, only: [:new, :index, :show, :create] do
    post 'join' => 'memberships#create'
    resources :challenges, only: [:create, :show, :index] do
      post 'join' => 'user_activities#create'
      post 'choose' => 'team_activities#create'
    end
  end
  resources :users, only: [:show] do
    resource :report, only: :show
  end
  resources :monthly_challenges, controller: :challenges
  resources :challenges, only: [:create, :show] do
    post 'join' => 'user_activities#create'
    resources :teams, only: [:new, :create, :show] do
      post 'join' => 'memberships#create'
    end
  end
  get '/contacts/:importer/callback' => 'contacts#contacts_callback'
  get '/contacts/contacts_callback'
  resources :user_invitation_team, only: [:new]
  devise_scope :user do
    match '/team/:id/invite' => 'invitations#team', via: [:get, :post]
    post 'batch_invite' => 'invitations#batch_invite'
    get '/registrations/resend' => 'registrations#resend'
    get '/registrations/welcome_page' => 'registrations#welcome_page'
    get '/introduction' => 'registrations#introduction'
    get '/update_profile' => 'registrations#update_profile'
  end
  get '/oauth2callback' => 'contacts#contacts_callback'
  resources :daily_activities, only: [:create, :update]
  resources :team_activities, only: :update
  resources :user_activities, only: :update
  post 'sync' => 'user_activities#sync'

  resources :identities, :only => :destroy
  get 'post_registrations' => 'social_sharing#post_registrations', as: :post_registrations
  post 'post_badge_won' => 'social_sharing#post_badge_won', as: :post_badge_won
  get 'post_challenge_join/:id' => 'social_sharing#post_challenge_join', as: :post_challenge_join
  get 'post_challenge_completion/:id' => 'social_sharing#post_challenge_completion', as: :post_challenge_completion

  resources :friendships, only: [:create, :edit, :destroy]

  resources :activity, only: [] do
    post 'wow' => 'activities#wow'
    delete 'unwow' => 'activities#unwow'
  end
  resources :action_messages, only: [:new] do
    collection { post :import }
  end
  resources :posts, only: [:create, :destroy]

  resources :comments, only: [:create, :destroy, :update] do
  end

  post '/request_invite' => 'users#request_invite', as: :request_invite
  get '/activities/view_more' => 'activities#view_more'

  get '/notifications/unread' => 'notifications#unread'
  put '/notifications/mark_as_read' => 'notifications#mark_as_read'
  get '/notifications/refresh' => 'notifications#refresh'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject, polymorphic: true
  acts_as_votable
  acts_as_commentable

  def photo
    subject.photo
    # begin
    #   if subject.is_a?(Achievement)
    #     subject.badge.photo
    #   else
    #     subject.photo
    #   end
    # rescue
    #   user.photo
    # end
  end

  def user_to_link_to
    subject
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  respond_to :html, :js
  def wow
    @activity = params[:class].constantize.find(params["activity_id"])
    @user = @activity.user
    @profile_user = User.find(session[:profile_id]) rescue nil
    @activity.liked_by current_user
  end

  def unwow
  	@activity = params[:class].constantize.find(params["activity_id"])
  	@user = @activity.user
    @profile_user = User.find(session[:profile_id]) rescue nil
    @activity.unliked_by current_user
  end

  def view_more
    if current_user.mutual_friends.count > 0
      @posts = Post.from_friends_of(current_user)
      user_ids = ([current_user.id] + current_user.friend_ids + current_user.inverse_friend_ids).join(',')
      @posts = @posts.where("creator_id IN (#{user_ids})").where("user_id IN (#{user_ids})")
    else
      @posts = current_user.posts
    end
    @num = params[:num].to_i
    @user = User.find(params[:user_id].to_i)
  end
end

app/views/activities/_activity.html.erb
<% # TODO: Indent properly and make it DRY! %>
<% if (current_user.eql? user) %>
  <% unless activity.deleted %>
    <li>
      <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12">
          <div class="col-md-2 col-xs-2 col-sm-2">
            <%= link_to image_tag(activity.photo.url(:thumb), size: '40x40'), activity.user_to_link_to %>
          </div>
          <div class="col-md-10 col-xs-10 col-sm-10">
            <% if activity.class == Post %>
              <% if (current_user.eql? user) %>
                <% if !activity.user.eql?(current_user) %>
                  <% if activity.image.exists? %>
                    <% if activity.creator.eql?(current_user) %>
                      You posted a picture on <%= link_to activity.user.user_name, activity.user %>'s page.
                    <% else %>
                      <% if activity.creator.eql?(activity.user) %>
                        <%= link_to activity.creator.user_name, activity.creator %> posted a picture:
                      <% else  %>
                        <%= link_to activity.creator.user_name, activity.creator %> posted a picture on <%=link_to activity.user.user_name, activity.user %>'s page
                      <% end %>
                    <% end %>
                  <% else %>
                    <% if activity.creator.eql?(current_user) %>
                      You posted on <%=link_to activity.user.user_name, activity.user %>'s page.
                    <% else %>
                      <% if activity.creator.eql?(activity.user) %>
                        <%= link_to activity.creator.user_name, activity.creator %> posted:
                      <% else  %>
                        <%= link_to activity.creator.user_name, activity.creator %> posted on <%= link_to activity.user.user_name, activity.user %>'s page
                      <% end %>
                    <% end %>
                  <% end %>
                <% else %>
                  <% if activity.image.exists? %>
                    <% if activity.creator.eql?(current_user) %>
                     You posted a picture:
                    <% else %>
                      <%= link_to activity.creator.user_name, activity.creator %> posted a picture on your page
                    <% end %>
                  <% else %>
                    <% if activity.creator.eql?(current_user) %>
                     You posted:
                    <% else %>
                      <%= link_to activity.creator.user_name, activity.creator %> posted on your page
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>

              <br><br>
              <p><%= activity.name.html_safe %></p>
              <% if activity.image.exists? %>
                <%= link_to image_tag(activity.image.url(:thumb)),activity.image.url(:large), data: { lightbox: activity.id } %>
                <% if @status %>
                  <%= @status.html_safe %>
                <% end %>
              <% end %>
            <% else %>
              <p><%= activity.name.html_safe %></p>
            <% end %>
            <div style="margin-top: 10px;">
              <span style="float:left;">
                <span id="activity_<%= activity.id %>_count"><%= render 'activities/wow_count', activity: activity %></span>
                <% if !(user.voted_for?(activity)) %>
                  <span id="activity_<%= activity.id %>_icon"><%= render 'activities/self_wow_icon', activity: activity %></span>
                  <span id="activity_<%= activity.id %>_comment_count"><%= render 'activities/comment_count', activity: activity %></span>
                  <%= link_to "javascript:void(0);" do %>
                    <i class="msgIcon" onclick="showComments('<%= activity.class.to_s %>','<%= activity.id %>')"></i>
                  <% end %>
                <% elsif (user.voted_for?(activity)) %>
                  <span id="activity_<%= activity.id %>_icon"><%= render 'activities/self_unwow_icon', activity: activity, user: user %></span>
                  <span id="activity_<%= activity.id %>_comment_count"><%= render 'activities/comment_count', activity: activity %></span>
                  <%= link_to "javascript:void(0);" do %>
                    <i class="msgIcon" onclick="showComments('<%= activity.class.to_s %>','<%= activity.id %>')"></i>
                  <% end %>
                <% end %>
              </span>
              <span id="time_ago" style="float:right;"><%= local_time_ago(activity.created_at) %></span>
            </div>
            <div class="CL"></div>
            <hr class="style-six" />
          </div>
          <div id="<%= activity.class.to_s %>-<%= activity.id %>" style="display: none;">
            <%= render 'shared/show_comments', commentable: activity, user: user %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
<% # I am not on my own profile so I am seeing someone else's profile. %>
<% else %>
  <li>
    <div class="row">
      <div class="col-md-12 col-xs-12 col-sm-12" style="margin-top: 1.3em;">
        <div class="col-md-2 col-xs-2 col-sm-2">
          <%= link_to image_tag(activity.photo.url(:thumb), size: '40x40'), activity.user_to_link_to %>
        </div>
        <div class="col-md-10 col-xs-10 col-sm-10" id="<%= activity.id%>">
          <% if activity.class == Post %>
            <% unless (current_user.eql? user) %>
              <% if activity.image.exists? %>
                <% if current_user.eql?(activity.creator) %>
                  You posted a picture:
                <% elsif current_user.eql?(activity.user) %>
                  <%= link_to activity.creator.user_name, activity.creator %> posted a picture on your page.
                <% elsif activity.user.eql?(user) %>
                  <%= link_to activity.creator.user_name, activity.creator %> posted a picture:
                <% elsif activity.user.eql?(user) && activity.creator.eql?(user)%>
                  <%= link_to activity.user.user_name, activity.user %> posted a picture:
                <% elsif !activity.user.eql?(user) && activity.creator.eql?(user)%>
                  <%= link_to activity.creator.user_name, activity.creator %> posted a picture on <%= link_to activity.user.user_name, activity.user %>'s page
                <% end %>
              <% else %>
                <% if current_user.eql?(activity.creator) && current_user.eql?(activity.user) %>
                  You posted on your page
                <% elsif activity.user.eql?(activity.creator) && !current_user.eql?(activity.user) %>
                  <%= link_to activity.creator.user_name, activity.creator %> posted:
                <% elsif current_user.eql?(activity.creator) && !current_user.eql?(activity.user) %>
                 You posted on <%= link_to activity.user.user_name, activity.user %>'s page
                <% elsif current_user.eql?(activity.user) %>
                  <%= link_to activity.creator.user_name, activity.creator %> posted on your page
                <% elsif activity.user.eql?(user) && !current_user.eql?(user) %>
                  <%= link_to activity.creator.user_name, activity.creator %> posted on <%= link_to activity.user.user_name, activity.user %>'s page
                <% elsif activity.user.eql?(user) && activity.creator.eql?(user)%>
                  <%= link_to activity.user.user_name, activity.user %> posted:
                <% elsif !activity.user.eql?(user) && activity.creator.eql?(user)%>
                  <%= link_to activity.creator.user_name, activity.creator %> posted on <%= link_to activity.user.user_name, activity.user %>'s page
                <% else %>
                  <%= link_to activity.creator.user_name, activity.creator %> posted on <%= link_to activity.user.user_name, activity.user %>'s page
                <% end %>
              <% end %>
            <% end %>
            <br><br>
            <p><%= activity.name.html_safe %></p>
            <% if activity.image.exists? %>
              <%= link_to image_tag(activity.image.url(:thumb)),activity.image.url(:large), data: { lightbox: activity.id }  %>
              <% if @status %>
                <%= @status.html_safe %>
              <% end %>
            <% end %>
          <% else %>
            <p> <%= activity.name.html_safe %></p>
          <% end %>
          <div style="margin-top: 10px;">
            <span style="float:left;">
              <span id="activity_<%= activity.id %>_count"><%= render 'activities/wow_count', activity: activity %></span>
              <% if !(current_user.voted_for? activity) %>
                <span id="activity_<%= activity.id %>_icon"><%= render 'activities/wow_icon', activity: activity, user: user %></span>
                <span id="activity_<%= activity.id %>_comment_count"><%= render 'activities/comment_count', activity: activity %></span>
                <%= link_to "javascript:void(0);" do %>
                  <i class="msgIcon" onclick="showComments('<%= activity.class.to_s %>','<%= activity.id %>')"></i>
                <% end %>
              <% elsif (current_user.voted_for? activity) %>
                <span id="activity_<%= activity.id %>_icon"><%= render 'activities/unwow_icon', activity: activity, user: user %></span>
                <span id="activity_<%= activity.id %>_comment_count"><%= render 'activities/comment_count', activity: activity %></span>
                <%= link_to "javascript:void(0);" do %>
                  <i class="msgIcon" onclick="showComments('<%= activity.class.to_s %>','<%= activity.id %>')"></i>
                <% end %>
              <% end %>
            </span>
            <span id="time_ago" style="float:right;"><%= local_time_ago(activity.created_at) %></span>
          </div>
          <div class="CL"></div>
        </div>
        <div id="<%= activity.class.to_s %>-<%= activity.id %>" style="display: none;">
          <%= render 'shared/show_comments', commentable: activity, user: user %>
        </div>
      </div>
    </div>
  </li>
<% end %>

app/views/activities/_comment_count.html.erb
<% if defined?(activity) %>
  <% commentors = User.where(id: activity.root_comments.pluck(:user_id)).pluck(:user_name) %>
<% elsif defined?(comment) %>
  <% commentors = User.where(id: comment.children.pluck(:user_id)).pluck(:user_name) %>
<% end %>
<span data-toggle="tooltip" data-html="true" data-placement="bottom" title='<%= commentors.join("<br>") rescue '' %>'>
  <% if defined?(activity) %>
    <%= activity.root_comments.count %>
  <% elsif defined?(comment) %>
    <%= comment.children.size %>
  <% end %>
</span>

app/views/activities/_self_unwow_icon.html.erb
<%= link_to image_tag('/wowdisable.png'), activity_unwow_path(activity,class:activity.class), method: :delete, id: "wow_#{activity.id}", disabled:  !(current_user.eql?(user) || (current_user.mutual_friends.include?(user))), style: 'padding-left:0px;',remote: true %>

app/views/activities/_self_wow_icon.html.erb
<%= link_to image_tag('/wowable.png'), activity_wow_path(activity,class:activity.class), method: :post, id: "wow_#{activity.id}", style: 'padding-left:0px;',remote: true %>

app/views/activities/_unwow_icon.html.erb
<% session[:profile_id] = user.id %>
<%= link_to image_tag('/wowdisable.png'), activity_unwow_path(activity,class:activity.class), method: :delete, id: "wow_#{activity.id}", disabled: !(current_user.mutual_friends.include?(user)), style: 'padding-left:0px;',remote: true %>

app/views/activities/_wow_count.html.erb
<span class="activity_status" id="activity_<%= activity.id %>" data-toggle="tooltip" data-html="true" data-placement="bottom" title='<%= User.where(id:activity.votes.pluck(:voter_id)).pluck(:user_name).join("<br>") %>'><%= activity.votes.size %></span>

app/views/activities/_wow_icon.html.erb
<% session[:profile_id] = user.id %>
<%= link_to image_tag('/wowable.png'), activity_wow_path(activity,class:activity.class), method: :post, id: "wow_#{activity.id}", disabled: !(current_user.mutual_friends.include?(user)), style: 'padding-left:0px;', remote: true %>

app/views/activities/unwow.js.erb
$("#activity_<%= @activity.id %>_count").html("<%= escape_javascript(render 'activities/wow_count', activity: @activity) %>");
$("#activity_<%= @activity.id %>_count").hide().fadeIn('slow');
<% if @profile_user %>
  $("#activity_<%= @activity.id %>_icon").html("<%= escape_javascript(render 'activities/wow_icon', activity: @activity, user: @profile_user) %>")
  $("#activity_<%= @activity.id %>_icon").hide().fadeIn('slow');
  <% session[:profile_id] = nil %>
<% else %>
  $("#activity_<%= @activity.id %>_icon").html("<%= escape_javascript(render 'activities/self_wow_icon', activity: @activity, user: current_user) %>")
  $("#activity_<%= @activity.id %>_icon").hide().fadeIn('slow');
<% end %>
$('body').tooltip({
    selector: '[rel=tooltip]'
});
$(".activity_status").tooltip();

app/views/activities/view_more.js.erb
$('#activity-spinner-<%= session[:activities_showing] %>').parent().fadeOut('fast');
<% session[:activities_showing] = @num+10 %>
var s = '<div><% (current_user.activities + @posts).sort{|a,b| b.created_at <=> a.created_at }.first(session[:activities_showing]).last(10).each do |activity| %><div id="<%= escape_javascript("activity_#{activity.id}_#{activity.class}") %>" ><%= escape_javascript(render "activities/activity", current_user: current_user, user: @user, activity: activity) %></div><% end %><p style="text-align: center; padding-bottom: 20px;"><%= escape_javascript(link_to 'View more ...', activities_view_more_path(num: session[:activities_showing], user_id: @user.id), method: :get, class: "colored-link", onclick: "$(this).parent().hide();$('#buzz').append(\"<div class='col-md-12' style='padding-bottom: 20px;'><div class='col-md-offset-5' id='activity-spinner-#{session[:activities_showing]}'><img src='/loader2.gif' width='40px;' /></div></div><div class='CL'></div>\");", remote: true)  %></p></div>';
var div = document.createElement('div');
div.innerHTML = s;

$('#buzz').append($(div.firstChild).hide().fadeIn('slow'));

app/views/activities/wow.js.erb
$("#activity_<%= @activity.id %>_count").html("<%= escape_javascript(render 'activities/wow_count', activity: @activity) %>");
$("#activity_<%= @activity.id %>_count").hide().fadeIn('slow');
<% if @profile_user %>
  $("#activity_<%= @activity.id %>_icon").html("<%= escape_javascript(render 'activities/unwow_icon', activity: @activity, user: @profile_user) %>");
  $("#activity_<%= @activity.id %>_icon").hide().fadeIn('slow');
  <% session[:profile_id] = nil %>
<% else %>
  $("#activity_<%= @activity.id %>_icon").html("<%= escape_javascript(render 'activities/self_unwow_icon', activity: @activity, user: current_user) %>");
  $("#activity_<%= @activity.id %>_icon").hide().fadeIn('slow');
<% end %>
$('body').tooltip({
    selector: '[rel=tooltip]'
});
$(".activity_status").tooltip();